"""error posts created

Revision ID: 81b843802f4f
Revises: f385dd7e97e5
Create Date: 2020-12-12 14:02:38.709037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b843802f4f'
down_revision = 'f385dd7e97e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unity_error', 'code_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unity_error', sa.Column('code_file', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
